baseurl = "http://onida-coaching.de"
languageCode = "en-us"
title = "ONIDA / Das Coaching"
#canonifyUrls = "true"
theme = "onida-theme"
[params]
    description = "Gruppencoaching für Ärztinnen in der Facharztausbildung"
