baseurl = "http://onida.github.io"
publishdir = "../"
languageCode = "de"
title = "ONIDA / Das Coaching"
#canonifyUrls = "true"
theme = "onida-theme"
[params]
    description = "Gruppencoaching für Ärztinnen in der Facharztausbildung"
